---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse" or "openSUSE Leap"

- name: create app_rewards directory
  file:
    path: "{{ app_rewards_dir }}"
    state: directory
    owner: "{{ app_rewards_user }}"
  tags: app_rewards

- name: setup systemd service file
  template:
    src: app_rewards.service.j2
    dest: /usr/lib/systemd/system/app_rewards.service
  register: app_rewards_service_update
  tags: app_rewards

- name: reload systemd config if service file is changed
  shell: systemctl daemon-reload
  when: app_rewards_service_update|changed
  tags: app_rewards

- name: start app_rewards service
  service:
    name: app_rewards
    state: started
  tags: app_rewards

- name: find os_family
  debug:
    msg: "{{ ansible_os_family }}"
  tags: app_rewards
