---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: create app_rewards directory
  file:
    path: "{{ app_rewards_dir }}"
    state: directory
    owner: "{{ app_rewards_user }}"
  tags: app_rewards

- name: reload systemd config if service file is changed
  shell: systemctl daemon-reload
  when: app_rewards_service_update|changed
  tags: app_rewards

- name: start app_rewards service
  service:
    name: app_rewards
    state: started
  tags: app_rewards
