---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: create folder for letsencrypt webroot validation method
  file:
    state: directory
    path: "{{ nginx_le_root }}"

- name: setup nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_main_conf_update
  
- name: add conf to conf.d 
  template:
    src: "{{ nginx_hostname }}.nginx.conf.j2"
    dest: /etc/nginx/conf.d/{{ nginx_hostname }}.nginx.conf
  register: nginx_confd_update

- name: reload nginx if config was updated
  service:
    name: nginx
    state: reloaded
  when: nginx_main_conf_update|changed or nginx_confd_update|changed

## Manual steps performed
## See guide: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
# Comment out ssl section of nginx.conf temporarily
# git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
# cd /opt/letsencrypt
# ./letsencrypt-auto certonly -a webroot --webroot-path=/var/www/letsencrypt -d "jenkins.joshuascheel.com"
## Add to root's crontab
# 0 0 1 * * /opt/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log
# 5 0 1 * * /bin/systemctl reload nginx
