---

- name: install nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: find ansible_hostname
  debug:
    msg: "{{ ansible_hostname }}"
  tags: nginx

- name: setup nginx.conf
  template:
    src: "{{ ansible_hostname }}.nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
  register: nginx_conf_update
  tags: nginx

- name: reload nginx is config was updated
  service:
    name: nginx
    state: reloaded
  when: nginx_conf_update|changed
  tags: nginx
