---

dependencies:
  - sudo
  - update
  - role: bash
    bash_global: "yes"
    bash_line: "export VISUAL=vim && export EDITOR=$VISUAL"
  - role: bash
    bash_global: "yes"
    bash_line: PS1="[\[\033[32m\]\w]\[\033[0m\]\n\[\033[1;36m\]\u\[\033[1;33m\]-> \[\033[0m\]"
    # bash_line: "PS1='{{'\"'}}\\[\\e[0;32m\\]\\u@\\h\\[\\e[m\\] \\[\\e[1;34m\\]\\w\\[\\e[m\\] \\[\\e[1;32m\\]\\$\\[\\e[m\\] \\[\\e[1;37m\\]{{'\"'}}'"
  - hosts
  # - landscape-client
  - firewall
  - role: authorized_keys
    linux_user: jscheel
    auth_key_list:
      - "{{ ssh_pubkey_jscheel_serenity }}"
      - "{{ ssh_pubkey_jscheel_pod }}"
  - swappiness
