---

- name: create app_allc directory
  file:
    path: "{{ app_allc_dir }}"
    state: directory
    owner: "{{ app_allc_user }}"

- name: deploy docker-compose.yml template
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_allc_dir }}/docker-compose.yml-example"
    owner: "{{ app_allc_user }}"
    group: "{{ app_allc_user }}"
