---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse"

- include: suse.yml
  when: ansible_os_family == "openSUSE Leap"
