---

- name: remove openjdk
  apt: name=*openjdk* state=absent
  tags: java8

- name: accept oracle license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  tags: java8

- name: add webupd8team/java
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
  tags: java8

- name: install oracle java 8
  apt:
    name: oracle-java8-installer
    state: present
  tags: java8
