---

- hosts: all
  vars_files:
    - .vault/secrets
  roles:
    - common
    - update-nightly

- hosts: virtualboxservers
  vars_files:
    - .vault/secrets
  roles:
    - virtualbox-guest

- hosts: jenkinsmasterservers
  vars_files:
    - .vault/secrets
  roles:
    - jenkins-master

- hosts: heatbeatservers
  vars_files:
    - .vault/secrets
  roles:
    - heatbeat

- hosts: allcalculatedservers
  vars_files:
    - .vault/secrets
  roles:
    - all_calculated

##########################
# SINGLE HOSTS DEV
##########################

- hosts: berry.homenet
  vars_files:
    - .vault/secrets
  roles:
    - { role: nginx, nginx_hostname: berry.homenet }
    - dht22
    
- hosts: htpc.homenet
  vars_files:
    - .vault/secrets
  roles:
    - { role: firewall, tcp_ports_allow: [5900] }
    - steam

- hosts: jenkins.homenet
  vars_files:
    - .vault/secrets
  roles:
    - { role: nginx, nginx_hostname: jenkins.homenet }

- hosts: pod.homenet
  vars_files:
    - .vault/secrets
  roles:
    - laptop
    - { role: nginx, nginx_hostname: pgadmin.homenet }

- hosts: serenity.homenet
  vars_files:
    - .vault/secrets
  roles:
    - desktop
    - { role: nginx, nginx_hostname: pgadmin.homenet }

##########################
# SINGLE HOSTS PROD
##########################

- hosts: joshuascheel.com
  vars_files:
    - .vault/secrets
  roles:
    # - { role: nginx, nginx_hostname: jenkins.joshuascheel.com }
    - { role: nginx, nginx_hostname: heatbeat.joshuascheel.com }
    - { role: nginx, nginx_hostname: ac.joshuascheel.com }
