---

- hosts: all
  vars_files:
    - .vault/secrets
  roles:
    - common
    - update-nightly

- hosts: virtualboxservers
  vars_files:
    - .vault/secrets
  roles:
    - virtualbox-guest

- hosts: jenkinsmasterservers
  vars_files:
    - .vault/secrets
  roles:
    - jenkins-master
    - { role: docker-engine, docker_user: jenkins }

- hosts: heatbeatservers
  vars_files:
    - .vault/secrets
  roles:
    - heatbeat

##########################
# SINGLE HOSTS DEV
##########################

- hosts: berry.homenet
  vars_files:
    - .vault/secrets
  roles:
    - { role: nginx, nginx_hostname: berry.homenet }
    - dht22
    
- hosts: pod.homenet
  vars_files:
    - .vault/secrets
  roles:
    - laptop
    - { role: nginx, nginx_hostname: pgadmin.homenet }

- hosts: htpc.homenet
  vars_files:
    - .vault/secrets
  roles:
    - { role: firewall, tcp_ports_allow: [5900] }
    - steam

##########################
# SINGLE HOSTS PROD
##########################

- hosts: joshuascheel.com
  vars_files:
    - .vault/secrets
  roles:
    - { role: nginx, nginx_hostname: jenkins.joshuascheel.com }
    - { role: nginx, nginx_hostname: heatbeat.joshuascheel.com }
