---

- name: create {{ heatbeat_user }} user
  user:
    name: "{{ heatbeat_user }}"
    generate_ssh_key: yes
    shell: "/bin/bash"

- name: add folder for heatbeat app
  become: true
  become_user: "{{ heatbeat_user }}"
  file:
    state: directory
    path: "{{ heatbeat_install_dir }}"

- name: checkout heatbeat git repo
  become: true
  become_user: "{{ heatbeat_user }}"
  git:
    repo: https://github.com/jscheel42/heatbeat.git
    dest: "{{ heatbeat_install_dir }}"
    accept_hostkey: yes
