---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: add vboxusers group
  group:
    name: "vboxusers"
    state: present
  tags: virtualbox-host

- name: add user to vboxusers
  user:
    name: "{{ virtualbox_user }}"
    groups: "vboxusers"
    append: yes
  tags: virtualbox-host
