---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse"

- include: suse.yml
  when: ansible_os_family == "openSUSE Leap"

- name: add vboxusers group
  group:
    name: "vboxusers"
    state: present
  tags: virtualbox-host

- name: add user to vboxusers
  user:
    name: "{{ virtualbox_user }}"
    groups: "vboxusers"
    append: yes
  tags: virtualbox-host
