---

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: setup symbolic link for Ansible to AnsibleVault
  file: src={{ git_ansible_vault_dir }} dest="{{ git_ansible_dir }}/.vault" mode=0755 state=link
  tags: workstation
