---

- name: ensure aptitude is installed
  apt:
    name: aptitude
    state: present

- name: update all apt packages
  apt:
    upgrade: yes
    update_cache: yes
  when: update_all_packages == "yes"
