---

dependencies:
  - role: git
    git_co_info:
      - { git_repo: "git@github.com:jscheel42/Ansible.git", git_dir: "{{ git_ansible_dir }}" }
      - { git_repo: "git@gitlab.com:jscheel42/ansiblevault.git", git_dir: "{{ git_ansible_vault_dir }}" }
      - { git_repo: "git@gitlab.com:jscheel42/all_calculated.git", git_dir: "{{ git_user_home }}/Projects/all_calculated" }
  # - role: ruby
  #   ruby_gems: [ bundler ]
  # - { role: jruby, jruby_gems: [ bundler ] }
  # - role: maven3
  #   linux_user: "jscheel"
  #   maven3_version_major: 3.3
  #   maven3_version_minor: 3
  #   maven3_default: "true"
  #   maven3_latest: "true"
  - role: postgresql
    postgresql_users: "{{ postgresql_allc_users }}"
    postgresql_databases: "{{ postgresql_allc_databases }}"
  - steam
  - virtualbox-host
  # - gradle
  # - grails
  # - play
  # - spring
  # - intellij
  # - pycharm
  # - netbeans
  # - eclipse
  - atom
  # - sublime
  - docker-engine
  - elixir-erlang-compile
  - java8
  - pgadmin4
