---

app_allc_user: "{{ app_user }}"
app_allc_home: /home/{{ app_allc_user }}
app_allc_dir: "{{ app_allc_home }}/app_allc"
app_allc_jar: "{{ app_allc_dir }}/allc.jar"

app_allc_port: 8181

app_allc_systemd_dir_ubuntu: /lib/systemd/system
app_allc_systemd_dir_suse: /usr/lib/systemd/system
