---

- name: add jpackage repository
  template: src=jpackage.repo.j2 dest=/etc/yum.repos.d/jpackage.repo
  tags: spacewalk-server

- name: add the spacewalk server repo
  yum: name={{ spacewalk_server_repo }} state=present update_cache=yes
  tags: spacewalk-server

- name: install spacewalk with preset postgres config
  yum: name={{ item }} state=present
  with_items:
    - "yum-priorities" # included to prioritize jpackage, as it holds a lower version cglib that parts of spacewalk need
    - "spacewalk-setup-postgresql"
    - "spacewalk-postgresql"
  tags: spacewalk-server

- name: create directory to hold tracking files
  file: path={{ spacewalk_server_tracking_dir }} state=directory
  tags: spacewalk-server

- name: read state from file on server
  shell: cat {{ spacewalk_server_tracking_file }}
  register: spacewalk_server_tracking_file_cat
  ignore_errors: yes
  changed_when: False
  tags: spacewalk-server

- name: copy answer file for spacewalk config
  template: src=answer-file.j2 dest={{ spacewalk_answer_file }} mode=0700 owner=root
  when: spacewalk_server_tracking_file_data != "setup_complete"
  tags: spacewalk-server

- name: configure spacewalk using answer file
  shell: bash -lc "spacewalk-setup --disconnected --answer-file={{ spacewalk_answer_file }}"
  when: spacewalk_server_tracking_file_data != "setup_complete"
  failed_when: not "'to create the Spacewalk administrator account' in command_result.stderr"
  register: spacewalk_server_installed
  tags: spacewalk-server

- name: add spacewalk tracking file
  shell: echo setup_complete > {{ spacewalk_server_tracking_file }}
  when: spacewalk_server_installed|changed
  tags: spacewalk-server

- name: remove the answer file
  file: path={{ spacewalk_answer_file }} state=absent
  tags: spacewalk-server
