---

- name: add jenkins repo key
  apt_key:
    url: http://pkg.jenkins.io/debian-stable/jenkins.io.key

- name: add jenkins repo
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

- name: install jenkins
  apt:
    name: jenkins
