
---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse"

- include: suse.yml
  when: ansible_os_family == "openSUSE Leap"

- name: create required directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ grails_install }}"
  tags: grails

- name: download grails archive
  get_url: url={{ grails_url }} dest={{ grails_archive }}
  tags: grails

- name: extract archive to install directory
  unarchive: src={{ grails_archive }} dest={{ grails_install }} copy=no mode=0755 owner=root group=root creates="{{ grails_install_target }}"
  tags: grails

- name: create latest symbolic link for grails
  file: src={{ grails_install_target }} dest={{ grails_install_latest }} mode=0755 state=link
  tags: grails

