---

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse" or "openSUSE Leap"

- name: setup .gitconfig
  template: src=.gitconfig.j2 dest={{ git_user_home }}/.gitconfig mode=0644 owner={{ git_user }}
  tags: git

- name: ensure destination(s) are present
  file: path={{ item.git_dir }} state=directory owner={{ git_user }} # group={{ git_user }}
  with_items: git_co_info
  when: item.git_repo != [] and item.git_dir != []
  tags: git

- name: checkout git repo
  # sudo_user: "{{ linux_user }}"
  git: repo={{ item.git_repo }} dest={{ item.git_dir }} accept_hostkey=true key_file={{ ssh_keyfile_private }} update={{ item.git_update if item.git_update is defined else "no" }}
  with_items: git_co_info
  when: item.git_repo != [] and item.git_dir != []
  tags: git

- name: assign owner to git repo
  file: path={{ item.git_dir }} state=directory owner={{ linux_user }}
  with_items: git_co_info
  when: item.git_repo != [] and item.git_dir != []
  tags: git
