---

- name: download atom rpm
  get_url:
    url: "{{ atom_url }}"
    dest: "{{ atom_rpm }}"
  register: atom_downloaded
  tags: atom

- name: install atom from rpm if download was performed
  yum:
    name: "{{ atom_rpm }}"
  when: atom_downloaded|changed
  tags: atom
