---

- name: add webupd8team/atom key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7B2C3B0889BF5709A105D03AC2518248EEA14886

- name: add webupd8team/atom
  apt_repository:
    repo: 'ppa:webupd8team/atom'
    state: present

- name: install atom
  apt:
    name: atom
    state: present
