---

- name: download atom deb
  get_url:
    url: "{{ atom_url_deb }}"
    dest: "{{ atom_deb }}"
  register: atom_downloaded
  tags: atom

- name: install atom from rpm if download was performed
  apt:
    deb: "{{ atom_deb }}"
  when: atom_downloaded|changed
  tags: atom
