---

## CHECK VERSION AND/OR EXISTANCE OF jenkins ON TARGET SERVER

- name: read version from file on server
  shell: cat {{ jenkins_version_file }}
  register: jenkins_version_cat
  ignore_errors: yes
  changed_when: False
  tags: jenkins

## REMOVE EXISTING INSTALLATION IF THE VERSION CHANGES

- name: remove existing jenkins installation if requested version differs from installed version
  shell: bash -lc "mv {{ jenkins_war }} /tmp/jenkins-deleted.war"
  when: jenkins_version_file_data != "" and jenkins_version_file_data != "{{ jenkins_version }}"
  tags: jenkins

- name: wait for autodeploy to remove jenkins tomcat folder if requested version differs from installed version
  wait_for: path={{ jenkins_deploy }} state=absent delay=20
  when: jenkins_version_file_data != "" and jenkins_version_file_data != "{{ jenkins_version }}"
  tags: jenkins

## INSTALL jenkins IF THE REQUESTED VERSION DOES NOT ALREADY EXIST

- name: download war to webapps directory
  get_url: url={{ jenkins_url }} dest={{ jenkins_war }} owner={{ tomcat_user }} # group={{ tomcat_user }}
  when: jenkins_version_file_data != "{{ jenkins_version }}"
  register: jenkins_installed
  notify: restart tomcat
  tags: jenkins

- name: wait for autodeploy to setup the jenkins directory
  wait_for: path={{ jenkins_deploy }} state=present delay=60
  when: jenkins_installed|changed
  notify: restart tomcat
  tags: jenkins

- name: write a new jenkins-version file if an installation occured
  template: src=jenkins-version.j2 dest={{ jenkins_version_file }} owner={{ tomcat_user }} # group={{ tomcat_user }}
  when: jenkins_installed|changed
  notify: restart tomcat
  tags: jenkins

- name: set jenkins as root context on tomcat server
  lineinfile:
    line: '<Context path="" docBase="jenkins" debug="0" reloadable="true"></Context>'
    insertbefore: "</Host>"
    dest: "{{ tomcat_conf_server }}"
  notify: restart tomcat
  tags: jenkins

# Reasoning for frequent tomcat restart notifies:
# If the root context app is replaced, it looks like tomcat needs a restart to load the conf/server.xml
# and set the new version of the root application to use the root context
