---

java8_version_minor: 74
java8_version: 8u{{ java8_version_minor }}
# The "-b27" in the url sometimes changes with versions and will need to be updated. Downloads fail without it, otherwise unsure of purpose.
java8_url: http://download.oracle.com/otn-pub/java/jdk/{{ java8_version }}-b02/jdk-{{ java8_version }}-linux-x64.tar.gz
java8_download_folder: /usr/local/src
java8_archive: "{{ java8_download_folder }}/jdk-{{ java8_version }}-linux-x64.tar.gz"
java8_install: /opt/jdk8-oracle
java8_install_latest: "{{ java8_install }}/latest"
java8_install_target: "{{ java8_install }}/jdk1.8.0_{{ java8_version_minor }}"

java8_openjdk_packages_suse:
  - java-1_7_0-openjdk
  - java-1_7_0-openjdk-headless
  - java-1_7_0-openjdk-plugin
  - java-1_8_0-openjdk
  - java-1_8_0-openjdk-headless
  - java-1_8_0-openjdk-plugin
