---

- name: find os_family
  debug:
    msg: "{{ ansible_os_family }}"
  tags: sudo

- name: add specified users to sudo group
  user:
    name: "{{ item }}"
    append: yes
    groups: "sudo"
  with_items: sudo_admin_list
  tags: sudo

- name: upload sudoers config
  template:
    src: debian_sudoers.j2
    dest: /etc/sudoers
    validate: 'visudo -cf %s'
  tags: sudo
