---

- name: add specified users to sudo group
  user:
    name: "{{ item }}"
    append: yes
    groups: "sudo"
  with_items: "{{ sudo_admin_list }}"

- name: upload sudoers config
  template:
    src: ubuntu_sudoers.j2
    dest: /etc/sudoers
    validate: 'visudo -cf %s'
