---

  # Only configuration is done if an install already exists

- name: create install directory
  file: path={{ androidstudio_install_dir }} state=directory
  register: androidstudio_install
  tags: androidstudio

- name: create required directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ androidstudio_tmp_dir }}"
  when: androidstudio_install|changed
  tags: androidstudio

- name: download androidstudio tar file
  get_url: url={{ androidstudio_url }} dest={{ androidstudio_archive }}
  when: androidstudio_install|changed
  tags: androidstudio

- name: extract androidstudio tar file
  unarchive: src={{ androidstudio_archive }} dest={{ androidstudio_tmp_dir }} copy=no
  when: androidstudio_install|changed
  tags: androidstudio

- name: move androidstudio folder to standard location
  shell: mv {{ androidstudio_tmp_dir }}/*/* {{ androidstudio_install_dir }}/
  when: androidstudio_install|changed
  tags: androidstudio

- name: set current user as owner of androidstudio directory
  file: path={{ androidstudio_install_dir }} owner={{ androidstudio_user }} recurse=yes state=directory # group={{ androidstudio_user }}
  when: androidstudio_install|changed
  tags: androidstudio

- name: setup executable in /usr/bin
  file: src="{{ androidstudio_install_dir }}/bin/studio.sh" dest=/usr/bin/androidstudio state=link
  tags: androidstudio

- name: setup desktop icon for androidstudio
  template: src=androidstudio.desktop.j2 dest=/usr/share/applications/androidstudio.desktop
  tags: androidstudio
