---

postgresql_version_major: 9
postgresql_version_minor: 5
postgresql_version: "{{ postgresql_version_major }}{{ postgresql_version_minor }}"

postgresql_dir_suse: "/data/pg-{{ postgresql_version }}"
postgresql_dir_ubuntu: "/etc/postgresql/{{ postgresql_version_major }}.{{ postgresql_version_minor }}/main"
postgresql_dir_centos: "/var/lib/pgsql/data"
postgresql_port: 5432
postgresql_listen_addr: "*"
postgresql_remote_allow: "yes"
postgresql_remote_domain: "all"

postgresql_users: []

postgresql_admins:
  - {name: "jscheel", perms: "SUPERUSER,LOGIN", password: "{{ secret_postgresql_password_jscheel_enc }}" }

postgresql_databases: []
