---

- name: add elrepo rpm key
  rpm_key: key="https://www.elrepo.org/RPM-GPG-KEY-elrepo.org"
  tags: elrepo

- name: install elrepo
  yum: name="http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm" state=present
  tags: elrepo

