---

- name: apply /etc/hosts config
  template: src=hosts.j2 dest=/etc/hosts
  register: hosts_update
  tags: hosts

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: suse.yml
  when: ansible_os_family == "Suse"

- include: suse.yml
  when: ansible_os_family == "openSUSE Leap"
