---

- name: install packages required for ruby
  apt: name={{ item }} state=present
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    # - openssl-devel
    # - readline-devel
    # - zlib-devel
